title: "Amine Jamal"
description: "MSc Embedded Systems | BSc Computer Science | Software Developer"
url: "https://AmineJml.github.io"
baseurl: ""

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

author:
  name: "Amine Jamal"
  email: "aminejamal003@gmail.com"

linkedin: "https://linkedin.com/in/amine-jamal-a06012220/"
github: "https://github.com/AmineJml"

show_downloads: false
