url: "https://AmineJml.github.io"
baseurl: ""
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: "Amine J. â€“ CS Student & Embedded / Systems Developer"
description: "Intro about mmyslef"
