title: "Amine Jamal"
description: "MSc Embedded Systems | BSc Computer Science | Software Developer"
url: "https://AmineJml.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

minimal_mistakes_skin: "dark"

author:
  name: "Amine Jamal"
  email: "aminejamal003@gmail.com"

linkedin: "https://linkedin.com/in/amine-jamal-a06012220/"
github: "https://github.com/AmineJml"

show_downloads: false
